.section .init
.global _init
_init:
    # Save the old base pointer
    pushq %rbp
    # Set up the new base pointer
    movq %rsp, %rbp
    # Initialization code goes here (usually generated by the compiler)
    popq %rbp
    ret
